import { describe, expect, test } from "vitest";
import jsQR from "jsqr";
import qrcode from "qrcode";

describe("QR roundtrip — qrcode → jsQR", () => {
  test("decodes a QR code generated by qrcode back to the original data", () => {
    const originalCode = "TICKET-UUID-001";

    // Use the low-level qrcode.create to get the QR matrix directly (no PNG parsing needed)
    const qr = qrcode.create(originalCode, { errorCorrectionLevel: "M" });
    const size = qr.modules.size;
    const data = qr.modules.data;

    // jsQR needs a minimum pixel size to detect a code — scale up 10x with a quiet zone margin
    const scale = 10;
    const margin = 4;
    const totalSize = (size + margin * 2) * scale;
    const rgba = new Uint8ClampedArray(totalSize * totalSize * 4);

    // White background
    rgba.fill(255);

    for (let row = 0; row < size; row++) {
      for (let col = 0; col < size; col++) {
        const isDark = data[row * size + col];
        const v = isDark ? 0 : 255;
        for (let dy = 0; dy < scale; dy++) {
          for (let dx = 0; dx < scale; dx++) {
            const px = ((row + margin) * scale + dy) * totalSize + (col + margin) * scale + dx;
            rgba[px * 4 + 0] = v;
            rgba[px * 4 + 1] = v;
            rgba[px * 4 + 2] = v;
            rgba[px * 4 + 3] = 255;
          }
        }
      }
    }

    const result = jsQR(rgba, totalSize, totalSize);

    expect(result).not.toBeNull();
    expect(result!.data).toBe(originalCode);
  });
});
